export const faceCapture = {
  modelAssetName: 'face-landmarker.task',
  maxInputDimension: 1600,
  minInputDimension: 160,
  qualitySampleDimension: 256,
  alignedFaceSize: 224,
  alignedFaceAspectRatio: 1,
  maxFaces: 10,
  minDetectionConfidence: 0.6,
  minPresenceConfidence: 0.6,
  minTrackingConfidence: 0.5,
  minLandmarkCount: 100,
  minFaceWidthRatio: 0.08,
  minFaceHeightRatio: 0.08,
  minFaceAreaRatio: 0.015,
  maxRollDegrees: 35,
  maxYawDegrees: 35,
  maxPitchDegrees: 30,
  minBrightness: 35,
  maxBrightness: 225,
  minSharpness: 8,
  cropWidthMultiplier: 1.8,
  cropHeightMultiplier: 1.55,
  cropPaddingRatio: 0.2,
  targetEyeDistanceRatio: 0.38,
  maxProcessingTimeMs: 30_000,
} as const;